### ISSUE TITLE
January 2016 doesn't seem to be working

### ISSUE THREAD

**Issue by jdlrobson** [tomayac/pageviews.js#1]
Not sure if intentional but confusing:

```
pageviews.getTopPageviews({
        project: 'en.wikipedia',
        year: 2016,
        month: 1,
        day: 1,
        limit: 15
    }).catch(function(error) {
      console.log(error);
    });
} );
```

Returns error [Error: Required parameter "month" missing or invalid.]
However
using month: "01" doesn't.
Using a number over 9 for day and month parameters however does work.
I would suggest testing for typeof Number and erroring out OR allowing numbers for these fields.

**Comment by jdlrobson** [comment]
Looks like it might have tripped up http://top.hatnote.com/ too which stopped updating ?

**Comment by tomayac** [comment]
Thanks for the report! I agree, this is confusing. It assumes a leading '0'
and type string (while for >10 integer works, too). I'll make this more
forgiving by allowing for both, zero-padded months and just plain integers.
Still in holiday mode, but expect a fix in the coming work week. Thanks
again :-)

**Comment by tomayac** [comment]
Fixed with https://github.com/tomayac/pageviews.js/commit/085250fabb86aad5225e8fa8ac147d30278464b4.
