### ISSUE TITLE
Add interface for new by country endpoint

### ISSUE THREAD

**Issue by fdansv** [tomayac/pageviews.js#12]
@tomayac we've added a new endpoint in the pageview API: top pageviews by country!

https://wikitech.wikimedia.org/wiki/Analytics/AQS/Pageviews#Pageviews_split_by_country

It'll probably be useful to add it to your wonderful library. The only caveat to bear in mind is that the views values is reported as a string representing a bucket (so instead of `"views": 7500` the api will return `"views": "1000-9999"`)

**Comment by tomayac** [comment]
@fdansv This is live as of v1.4.0. Hope this works as intended.
