### ISSUE TITLE
Code hangs in the main npm script

### ISSUE THREAD

**Issue by joscelyn** [tomayac/pageviews.js#16]
Hello,

Firstly, thanks for this well code wikimedia client !

Just to inform that there is a code at the bottom of the script that console.log each time we required it : 
`
pageviews.getTopPageviewsByCountry({
      project: 'fr.wikipedia',
      year: 2017,
      month: 12,
  access: 'mobile-web'
    }).then(function(result) {
      console.log(JSON.stringify(result, null, 2))
    });
`

Have a nice day

**Comment by tomayac** [comment]
Oops, sorry for the oversight. Just [published v1.4.2](https://www.npmjs.com/package/pageviews) that fixes this. That being said, you probably want to include the [minified library](https://github.com/tomayac/pageviews.js/blob/master/pageviews.min.js) that didn't have the logs.
