### ISSUE TITLE
Browser example doesn't work

### ISSUE THREAD

**Issue by YairRand** [tomayac/pageviews.js#18]
When running the [browser example](https://github.com/tomayac/pageviews.js#usage-in-the-browser) given in the readme, the only output is `{
  "isTrusted": true
}`. (My guess is that it's probably a CORS issue.)

**Comment by YairRand** [comment]
Ack, sorry, this issue was just a mistake on my end. It works otherwise. Closing.

**Comment by tomayac** [comment]
Awesome, thanks for letting me know. I was just about to put this on the “needs further investigation” pile when I realized it worked normally on my end. Happy it’s a non-issue instead. 😃
