### ISSUE TITLE
Wikidata project 

### ISSUE THREAD

**Issue by nuria** [tomayac/pageviews.js#4]
Let me know if you want a pull request for this one too: "wikidata" is also a valid project. 

See:
https://wikimedia.org/api/rest_v1/metrics/pageviews/aggregate/wikidata/all-access/user/daily/2015010100/2016030712

Thank you.

**Comment by nuria** [comment]
Projects can be found here, although many of them are not used any more: https://meta.wikimedia.org/w/api.php?action=sitematrix&formatversion=2&format=json

**Comment by nuria** [comment]
Nevermind, turns out we are going to program a bit more defensively and have api accept www.wikidata.org and such.  Still, I think it will be good not to assume that projects always have "."

Will work on PR

**Comment by tomayac** [comment]
Cool, thanks :-) On a two-week vacation at the moment, merges might take a bit longer than usual, but will happen eventually ;-)

**Comment by tomayac** [comment]
Closed with https://github.com/tomayac/pageviews.js/commit/dfbc7b5d5524dc7f0e64af955a008a015581d892. Thanks for raising the issue!
