### ISSUE TITLE
Problems when transforming Date object to string

### ISSUE THREAD

**Issue by marcelrf** [tomayac/pageviews.js#5]
Hi Thomas,
Thank you very much for creating this awesome lib!

I think I found two problems in the code that transforms a Date object into a string. I filed just one issue for both, because they are caused by the same couple lines of code. If they make sense, please let me know if you want me to create a pull request for that. Thanks :)

**1. Passing a Date object belonging to October, November or December fails validation.**
When building a date string from a Date object:

```
var pad = function(d) {
    return d < 10 ? '0' + d : d;
};

...

params.start = typeof params.start === 'object' ?
    (params.start.getFullYear() + (pad(params.start.getMonth() + 1)) +
        pad(params.start.getDate())) :
    params.start;
```

`getFullYear`, `getMonth` and `getDate` return numeric values. And `pad` only returns a string when actually padding. If the month is October, November or December, `pad` will return the value as is (numeric), and the concatenation will become a numerical sum, resulting in a validation error in the next regular expression check.

**2. Passing a Date object with time zone information may result in shifted dates.**
If the machine executing pageview.js has a timezone like GMT-5 and it tries to execute:

```
var pageviews = require('pageviews');

pageviews.getAggregatedPageviews({
    project: 'all-projects',
    granularity: 'daily',
    start: new Date('2016-01-01'),
    end: new Date('2016-01-31')
});
```

`new Date('2016-01-01')` will create a Date object with the following value `Thu Dec 31 2015 19:00:00 GMT-0500 (EST)`. And the code that generates a date string uses `getFullYear`, `getMonth` and `getDate`, which in this particular case will return `2015`, `12` and `31` respectively, generating a date string like `2015-12-31` instead of `2016-01-01`. This would happen with the end date as well.

Cheers!

**Comment by tomayac** [comment]
Hi @marcelrf, 

Thanks for filing this issue. Judging from your concrete description, you have the cause of the issue already identified, so if you file a quick pull request, I am happy to merge it straight away (and maybe you could even add a test case or two, so that such errors get caught the next time). Thanks for your help :-) !¡Muy apreciado!

Cheers,
Tom

**Comment by marcelrf** [comment]
Hi @tomayac :]

I created a pull request as you said. I could not manage to test the "negative timezone" scenario, though. It seems that JavaScript does not allow changing the locale of the browser. Anyway, I tried to make the tests as useful as possible.

Thanks for being open to my contribution!

Marcel
