### ISSUE TITLE
Does not seem to be working on Firefox at the moment

### ISSUE THREAD

**Issue by symac** [tomayac/pageviews.js#9]
Hello,
I have tried your JS library following some issues I had with some legacy script of mine that was doing kind of the same thing and I notice the same issue with your library than with my code, so maybe you'll be better than me at finding a solution to fix this :)

The thing is, using a very basic HTML page containing the example from the README ( https://gist.github.com/symac/c98233f11f4a3006a50f4728bda5287a ), I have a page that works as expected using Chrome or Opera but not on Firefox. When working correctly I get the pageviews statistics, but the console of Firefox just displays : 
`
{
  "isTrusted": true
}
`
and no pageviews data :(

I have not been able to find any error message so if any of you has an idea on how to fix this, I would be very happy to read you! I am using FF 53.0 64 bits on Linux.

**Comment by tomayac** [comment]
@symac I just tried your [example](https://gist.github.com/symac/c98233f11f4a3006a50f4728bda5287a) on both Firefox 53.0 (64-bit) and Firefox Nightly 55.0a1 (2017-05-04) (64-bit) on macOS and it just worked fine (side notes: you include the script [twice](https://gist.github.com/symac/c98233f11f4a3006a50f4728bda5287a#file-test-html-L7-L8) by accident and not sure you need [this](https://gist.github.com/symac/c98233f11f4a3006a50f4728bda5287a#file-test-html-L5) meta tag). Are you really using the [latest version](https://github.com/tomayac/pageviews.js/blob/master/pageviews.min.js) of the library? Also, could you check the Network tab in the Developer Tools to see if the request is being made?

**Comment by symac** [comment]
On another computer and another network at the moment it seems to work, will double check tomorrow, that might be an issue with the network I was using earlier to test or some extensions on the other firefox that were generating conflicts :(

S.

**Comment by tomayac** [comment]
Alright, I close the Issue for now, let me know if the problem persists and I am happy to reopen it.

**Comment by symac** [comment]
Just for information, if anybody was finding this issue, this is a conflict with the [uBlock origin](https://addons.mozilla.org/fr/firefox/addon/ublock-origin/) extension which seems to intercept some traffic and block it.

**Comment by tomayac** [comment]
Thanks for solving the mystery ;-)
